spring:
  profiles:
    active: dev

---
server:
  port: 8201
  
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost1:7001/eureka/

---
server:
  port: 8202
  
spring:
  profiles: test
  application:
    name: springcloud-config-test

eureka:
  client:
    service-url:
      defaultZone: http://localhost2:7002/eureka/